### ISSUE TITLE
Dummy's installation guide

### ISSUE THREAD

**Issue by ahope1** [bchiha/dungeon-of-doom#1]
Could you please write a quick idiot's guide to installing and running this? (I'm on a Mac, OS X 10.10.5.) Never used Ruby before. Can't find my way through the jungle of bundles and gems.

**Comment by bchiha** [comment]
Hey There.

Thanks for showing interest. Its been a while since I got it running but
will set it up for my Mac and update the guide. Give me a few days.

**Comment by ahope1** [comment]
Please do! Thank you.

**Comment by ahope1** [comment]
Btw, this is what prompted me to seek out your port:

http://www.usborne.com/catalogue/feature-page/computer-and-coding-books.aspx

**Comment by ahope1** [comment]
I mean, I've downloaded the zip and done this:

`$ sudo gem build dungeon-of-doom.gemspec` 
`fatal: Not a git repository (or any of the parent directories): .git`
`fatal: Not a git repository (or any of the parent directories): .git`
`fatal: Not a git repository (or any of the parent directories): .git`
`WARNING:  licenses is empty`
`WARNING:  no homepage specified`
`Successfully built RubyGem`
`Name: dungeon-of-doom`
`Version: 0.0.1`
`File: dungeon-of-doom-0.0.1.gem`
`$ sudo gem install dungeon-of-doom`
`Successfully installed dungeon-of-doom-0.0.1`
`Parsing documentation for dungeon-of-doom-0.0.1`
`Installing ri documentation for dungeon-of-doom-0.0.1`
`1 gem installed`

But what then? I've tried running the ruby scripts, but they seem to do nothing.

Obviously I have no idea what I'm doing.

**Comment by bchiha** [comment]
Okay. There are some bin files that I haven't put in github yet. They are
needed to run the three programs.  Sorry I've been a bit busy. I'll put
them up today.
I'm also having some character set problems on my computer so working on
that too.

Thanks for the usbourne link. The books seem to be missing pages. While you
are waiting for me to get the program working you can peruse my BBC books

https://app.box.com/s/nbggyydjvb22je8m9bn0xnszdu4wav7r

**Comment by bchiha** [comment]
I've updated the guide as requested.  The game should work now with the binaries.  Let me know what you think...I've also included the original bbc code and pdf instructions.  The gem stuff you did before is not needed to get this game to run.  I can't remember why I added it.

**Comment by ahope1** [comment]
Excellent work! Back in the day, I could never get this game to work on my Beeb! Great to finally see it debugged(?) and running, and also ported to Ruby, no less! 

Great book collection too. I remember the Usborne illustrations well, but some of the other books were new to me.

Thanks for rebuilding the Dungeon Of Doom.

**Comment by ahope1** [comment]
See also: http://stardot.org.uk/forums/viewtopic.php?f=41&t=10716&p=131258#p131258

**Comment by bchiha** [comment]
The main problem with the BBC code is saving the dungeon to tape.  I changed it to save the each level as a separate file to disk labelled as `LEVELx`, where x is the level number.  The main program keeps the level counter to find the next file.  I probably fixed some other bugs up too like with casting spells

Also, I added extra stats to the bottom of the screen, ATT, your attack power (weapon strength), spell count, candle count and potion count.  These stats are there, just not displayed.  I thought they will be useful to show.

Let me know if you can get the ruby version to work.  And thanks for the write up!

**Comment by ahope1** [comment]
Wow, sounds like you fixed and improved the game quite a bit. Usborne could have used you thirty years ago!

Yes, I got the Ruby version to work. (On my Mac, "ruby --version" reports "ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]", whatever that means.) Many thanks!

**Comment by ahope1** [comment]
Your Beeb version of Dungeon Of Doom (slightly updated) can now be played online at bbcmicro.co.uk:

http://bbcmicro.co.uk/game.php?id=3073

**Comment by bchiha** [comment]
Hey There,

Thanks for uploading it.  I'm slightly thrilled!  The intro menu looks
great and thanks for the keyboard help updates.

When I developed the game I created a hero file and 3 levels.  You could
upload them to the game.  They are a bit more complete than what is on
there..  Have a look at the attached disk


Thanks,
Brian

**Comment by ahope1** [comment]
Excellent! Thank you. Uploaded your levels and hero to bbcmicro.co.uk.
